### PR TITLE
fix exclude by message(s)

### PR DESCRIPTION
**Pull request by LeroyR**
Calculation of the text cell was all wrong.
Also there are 7 cells per row (id# is cell 0)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please describe the steps to reproduce what wasn't working without this patch and works with this patch.

**Comment by LeroyR** [comment]
From memory:
1. "Exclude by Message" creates regex filter using the message string but does not escape anything. Finding cases where this breaks is an exercise left for the reader of this comment.
2. Selecting multiple messages and creating filters for them results in garbage filters as the wrong column gets selected as input beyond the first.

Steps to reproduce:

1. Select Multiple Rows
2. Right Click -> Exclude by Message
3. Look at the Filters

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Comment by dirk-thomas** [comment]
Cherry-picked to the `dashing-devel` branch: 76ecf1b155c063407fcd808a95d587091aa30a18.

**Pull request merged**
